# Generated by Django 3.2.8 on 2021-10-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar_pet.png', upload_to=''),
        ),
    ]
