# Generated by Django 3.2.8 on 2021-10-21 13:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20211021_1642'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='relationship',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
